### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [asdf2014/yuzhouwan#42]
Hi
The following lines have cryptographic API misuses. <br> File name => yuzhouwan-hacker/src/main/java/com/yuzhouwan/hacker/security/GenerateKey.java: Line number => 26: API name => KeyGenerator:<BR> File name => yuzhouwan-hacker/src/main/java/com/yuzhouwan/hacker/security/SecurityClassLoader.java: Line number => 34: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to update, doFinal<BR> File name => yuzhouwan-hacker/src/main/java/com/yuzhouwan/hacker/security/EncryptClasses.java: Line number => 49: API name => Cipher:<BR> File name => yuzhouwan-hacker/src/main/java/com/yuzhouwan/hacker/security/EncryptClasses.java: Line number => 49: API name => Cipher:<BR> File name => yuzhouwan-hacker/src/main/java/com/yuzhouwan/hacker/security/GenerateKey.java: Line number => 24: API name => KeyGenerator:First parameter (with value "DES") should be any of {AES, Blowfish, DESede, HmacSHA224, HmacSHA256, HmacSHA384, HmacSHA512}<BR> File name => yuzhouwan-hacker/src/main/java/com/yuzhouwan/hacker/security/EncryptClasses.java: Line number => 39: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[])>, <javax.crypto.Cipher: byte[] doFinal(byte[])>, <javax.crypto.Cipher: int doFinal(java.nio.ByteBuffer,java.nio.ByteBuffer)>, update, <javax.crypto.Cipher: byte[] doFinal(byte[],int,int)>, <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[],int)><BR>

**Comment by asdf2014** [comment]
@mhp0rtal Thank you very much for pointing this out! Can you solve them?
